# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('year', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='zone_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone'),
        ),
        migrations.AddField(
            model_name='incident',
            name='zone_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone'),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zone'),
        ),
    ]
