# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_incident_norm_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
