# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_score_raw_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(),
        ),
    ]
