# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170228_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(),
        ),
    ]
